/*
 * serial-sniffer -- a serial port sniffer and logger
 *
 * Copyright (C) 2021 Jürgen Reuter
 *
 * This file is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation; either version 2 of the License,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 * 02111-1307, USA.
 *
 * As a special exception to the GNU General Public License, if you
 * distribute this file as part of a program that contains a
 * configuration script generated by Autoconf, you may include it
 * under the same distribution terms that you use for the rest of that
 * program.
 *
 * For updates and more info or contacting the author, visit:
 * <https://github.com/soundpaint/serial-sniffer>
 *
 * Author's web site: www.juergen-reuter.de
 */

#ifndef CONFIG_READER_HH
#define CONFIG_READER_HH

#include <xercesc/dom/DOM.hpp>
#include <abstract-config-reader.hh>
#include <config.hh>

class Config_reader : public Abstract_config_reader
{
public:
  Config_reader(Config *config);
  virtual ~Config_reader();
protected:
  virtual void parse_document(const xercesc::DOMElement *elem_config);
  virtual void print_config() const;
private:
  Config *_config;
  void parse_devices(const xercesc::DOMElement *elem_devices);
  void parse_logging(const xercesc::DOMElement *elem_logging);
  void parse_kiosk_mode(const xercesc::DOMElement *elem_kiosk_mode);
  void parse_key_bindings(const xercesc::DOMElement *elem_key_bindings);

  void parse_action(const xercesc::DOMElement *elem_action);
  void parse_keys(const xercesc::DOMElement *elem_keys,
                  const IKey_bindings::Action action);
  void parse_key(const xercesc::DOMElement *elem_key,
                 const IKey_bindings::Action action);
  void parse_audio(const xercesc::DOMElement *elem_audio);
  void parse_serial_parity_bit(const xercesc::DOMElement *elem_parity_bit);
  const XMLCh *parse_path(const xercesc::DOMElement *elem_device);
};

#endif /* CONFIG_READER_HH */

/*
 * Local variables:
 *   mode: c++
 *   coding: utf-8
 * End:
 */
