/*
 * serial-sniffer -- a serial port sniffer and logger
 *
 * Copyright (C) 2021 Jürgen Reuter
 *
 * This file is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation; either version 2 of the License,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 * 02111-1307, USA.
 *
 * As a special exception to the GNU General Public License, if you
 * distribute this file as part of a program that contains a
 * configuration script generated by Autoconf, you may include it
 * under the same distribution terms that you use for the rest of that
 * program.
 *
 * For updates and more info or contacting the author, visit:
 * <https://github.com/soundpaint/serial-sniffer>
 *
 * Author's web site: www.juergen-reuter.de
 */

#ifndef CONFIG_PANEL_HH
#define CONFIG_PANEL_HH

#include <QtWidgets/QComboBox>
#include <QtWidgets/QFormLayout>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>
#include <app-control.hh>
#include <log-config-panel.hh>
#include <serial-config-panel.hh>

class Config_panel : public QWidget
{
  Q_OBJECT
public:
  explicit Config_panel(App_control *app_control,
                        QWidget *parent);
  virtual ~Config_panel();
public slots:
  void save_values();
  void load_values();
  void dirty_changed();
  const bool get_dirty() const;
private:
  App_control *_app_control;
  QVBoxLayout *_layout;
  QWidget *_buttons_panel;
  QHBoxLayout *_buttons_layout;
  Serial_config_panel *_serial_config_panel;
  Log_config_panel *_log_config_panel;
  QPushButton *_button_reset;
  QPushButton *_button_apply;
  void create_actions();
};

#endif /* CONFIG_PANEL_HH */

/*
 * Local variables:
 *   mode: c++
 *   coding: utf-8
 * End:
 */
