/*
 * serial-sniffer -- a serial port sniffer and logger
 *
 * Copyright (C) 2021 Jürgen Reuter
 *
 * This file is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation; either version 2 of the License,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 * 02111-1307, USA.
 *
 * As a special exception to the GNU General Public License, if you
 * distribute this file as part of a program that contains a
 * configuration script generated by Autoconf, you may include it
 * under the same distribution terms that you use for the rest of that
 * program.
 *
 * For updates and more info or contacting the author, visit:
 * <https://github.com/soundpaint/serial-sniffer>
 *
 * Author's web site: www.juergen-reuter.de
 */

#include <control-panel.hh>
#include <log.hh>

Control_panel::Control_panel(App_control *app_control, QWidget *parent)
  : QWidget(parent)
{
  if (!app_control) {
    Log::fatal("Control_panel::Control_panel(): app_control is NULL");
  }
  _app_control = app_control;

  _layout = new QVBoxLayout();
  if (!_layout) {
    Log::fatal("Control_panel::Control_panel(): not enough memory");
  }
  setLayout(_layout);

  _control_console_logger_panel =
    new Control_console_logger_panel(_app_control, this);
  if (!_control_console_logger_panel) {
    Log::fatal("Control_panel::Control_panel(): not enough memory");
  }
  _layout->addWidget(_control_console_logger_panel);

  _control_file_logger_panel =
    new Control_file_logger_panel(_app_control, this);
  if (!_control_file_logger_panel) {
    Log::fatal("Control_panel::Control_panel(): not enough memory");
  }
  _layout->addWidget(_control_file_logger_panel);

  _control_serial_ports_panel =
    new Control_serial_ports_panel(_app_control, this);
  if (!_control_serial_ports_panel) {
    Log::fatal("Control_panel::Control_panel(): not enough memory");
  }
  _layout->addWidget(_control_serial_ports_panel);

  create_actions();
}

Control_panel::~Control_panel()
{
  // locally managed Qt objects
  _layout->deleteLater();
  _layout = 0;
  _control_console_logger_panel->deleteLater();
  _control_console_logger_panel = 0;
  _control_file_logger_panel->deleteLater();
  _control_file_logger_panel = 0;
  _control_serial_ports_panel->deleteLater();
  _control_serial_ports_panel = 0;

  // elsewhere managed objects
  _app_control = 0;
}

ILogger_status_listener *
Control_panel::get_logger_control_panel()
{
  return _control_console_logger_panel;
}

void
Control_panel::create_actions()
{
  // TODO
}

/*
 * Local variables:
 *   mode: c++
 *   coding: utf-8
 * End:
 */
