/*
 * serial-sniffer -- a serial port sniffer and logger
 *
 * Copyright (C) 2021 Jürgen Reuter
 *
 * This file is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation; either version 2 of the License,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 * 02111-1307, USA.
 *
 * As a special exception to the GNU General Public License, if you
 * distribute this file as part of a program that contains a
 * configuration script generated by Autoconf, you may include it
 * under the same distribution terms that you use for the rest of that
 * program.
 *
 * For updates and more info or contacting the author, visit:
 * <https://github.com/soundpaint/serial-sniffer>
 *
 * Author's web site: www.juergen-reuter.de
 */

#ifndef ILINE_INFO_HH
#define ILINE_INFO_HH

#include <string>

class ILine_info
{
public:
  enum line_type_t {
    rx, tx
  };
  static const std::string STR_RX;
  static const std::string STR_TX;
  virtual const uint32_t get_id() const = 0;
  virtual const std::string get_name() const = 0;
  virtual const std::string get_full_name() const = 0;
  virtual const line_type_t get_line_type() const = 0;
  virtual const std::string to_string() const = 0;
};

#endif /* ILINE_INFO_HH */

/*
 * Local variables:
 *   mode: c++
 *   coding: utf-8
 * End:
 */
