/*
 * serial-sniffer -- a serial port sniffer and logger
 *
 * Copyright (C) 2021 Jürgen Reuter
 *
 * This file is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation; either version 2 of the License,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 * 02111-1307, USA.
 *
 * As a special exception to the GNU General Public License, if you
 * distribute this file as part of a program that contains a
 * configuration script generated by Autoconf, you may include it
 * under the same distribution terms that you use for the rest of that
 * program.
 *
 * For updates and more info or contacting the author, visit:
 * <https://github.com/soundpaint/serial-sniffer>
 *
 * Author's web site: www.juergen-reuter.de
 */

#ifndef LOG_PANEL_HH
#define LOG_PANEL_HH

#include <vector>
#include <QtWidgets/QWidget>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QPushButton>
#include <app-control.hh>
#include <iconsole-logger.hh>
#include <ilogger-status-listener.hh>
#include <log-panel-list.hh>

class Log_panel
  : public QWidget, public IConsole_logger, public ILogger_status_listener
{
  Q_OBJECT
public:
  explicit Log_panel(App_control *app_control,
                     QWidget *parent);
  virtual ~Log_panel();
  void add_status_listener(ILogger_status_listener *listener);
  void remove_status_listener(ILogger_status_listener *listener);
  void update_events(const std::vector<Serial_event> *_events);
  virtual void stream_started();
  virtual void stream_stopped();
  virtual void logger_started();
  virtual void logger_stopped();
  virtual void notify_event(const Serial_event *event);
public slots:
  void start();
  void stop();
  void clear();
private:
  std::vector<ILogger_status_listener *> *_status_listeners;
  App_control *_app_control;
  QVBoxLayout *_layout;
  QWidget *_buttons_panel;
  QHBoxLayout *_buttons_layout;
  Log_panel_list *_log_panel_list;
  QPushButton *_button_clear;
  QPushButton *_button_start;
  QPushButton *_button_stop;
  void create_actions();
};

std::ostream &operator <<(std::ostream &os, const Log_panel &log_panel);

#endif /* LOG_PANEL_HH */

/*
 * Local variables:
 *   mode: c++
 *   coding: utf-8
 * End:
 */
