/*
 * serial-sniffer -- a serial port sniffer and logger
 *
 * Copyright (C) 2021 Jürgen Reuter
 *
 * This file is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation; either version 2 of the License,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 * 02111-1307, USA.
 *
 * As a special exception to the GNU General Public License, if you
 * distribute this file as part of a program that contains a
 * configuration script generated by Autoconf, you may include it
 * under the same distribution terms that you use for the rest of that
 * program.
 *
 * For updates and more info or contacting the author, visit:
 * <https://github.com/soundpaint/serial-sniffer>
 *
 * Author's web site: www.juergen-reuter.de
 */

#ifndef SERIAL_EVENT_DEFAULT_FILTER_HH
#define SERIAL_EVENT_DEFAULT_FILTER_HH

#include <serial-event-filter.hh>

class Serial_event_default_filter : public Serial_event_filter
{
public:
  Serial_event_default_filter(const ILine_info *line_info,
                              const Serial_event::event_type_t event_type);
  virtual ~Serial_event_default_filter();
  const bool accept0(const Serial_event *event) const;
  const ILine_info *get_line_info() const;
  void set_line_info(const ILine_info *line_info);
  const Serial_event::event_type_t get_event_type() const;
  void set_event_type(const Serial_event::event_type_t event_type);
private:
  const ILine_info *_line_info;
  Serial_event::event_type_t _event_type;
};

#endif /* SERIAL_EVENT_DEFAULT_FILTER_HH */

/*
 * Local variables:
 *   mode: c++
 *   coding: utf-8
 * End:
 */
